---
title:               Zach Sherman
tagline:             Programming Design Entrepreneurship
login:               zsherman
password:            origami
name:                Zach Sherman
twitter:             zach_h_sherman
github:              zsherman
email:               zksherm@gmail.com
google_analytics_id: YOUR_GA_ID
